markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  
remote_theme: vfvong/jekyll-theme-tao
